---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/webdecod/docs.devsbuddy.com/
    - rm -rf /home4/webdecod/docs.devsbuddy.com/tailwind-cli/assets/
    - /bin/cp -R .vitepress/tailwind-cli $DEPLOYPATH